package constants

const GitHubOwner = "NubeIO"
const SettingUUID = "set_123456789ABC"
const Eth0 = "eth0"
const Eth1 = "eth1"
const ConfigEnv = ".env"
const ConfigYml = "config.yml"
const BacnetServerDriver = "driver-bacnet"
const BacnetServerServiceName = "nubeio-driver-bacnet"
const RubixEdgeWiresServiceName = "nubeio-rubix-edge-wires"
const FlowFramework = "flow-framework"
const RubixIO16Repo = "rubix-io-fw"
const Edge28App = "driver-edge28"
const RubixIOApp = "driver-rubix-compute-io"
const RubixEdgeWires = "rubix-edge-wires"
const RubixWires = "rubix-wires"
const LoRaSerialApp = "driver-lora"

const CSUname = "admin"
const CSPassword = "Helensburgh2508"
